var hierarchy =
[
    [ "Jmcpp::Authorization", "struct_jmcpp_1_1_authorization.html", null ],
    [ "Jmcpp::ChatId", "class_jmcpp_1_1_chat_id.html", null ],
    [ "Jmcpp::Client", "class_jmcpp_1_1_client.html", null ],
    [ "Jmcpp::Configuration", "struct_jmcpp_1_1_configuration.html", null ],
    [ "Jmcpp::ContentBase", "struct_jmcpp_1_1_content_base.html", [
      [ "Jmcpp::CustomContent", "struct_jmcpp_1_1_custom_content.html", null ],
      [ "Jmcpp::FileContent", "struct_jmcpp_1_1_file_content.html", null ],
      [ "Jmcpp::ImageContent", "struct_jmcpp_1_1_image_content.html", null ],
      [ "Jmcpp::LocationContent", "struct_jmcpp_1_1_location_content.html", null ],
      [ "Jmcpp::NullContent", "struct_jmcpp_1_1_null_content.html", null ],
      [ "Jmcpp::TextContent", "struct_jmcpp_1_1_text_content.html", null ],
      [ "Jmcpp::VoiceContent", "struct_jmcpp_1_1_voice_content.html", null ]
    ] ],
    [ "Jmcpp::EventBase", "struct_jmcpp_1_1_event_base.html", [
      [ "Jmcpp::AddedToGroupEvent", "struct_jmcpp_1_1_added_to_group_event.html", null ],
      [ "Jmcpp::BlackListUpdatedEvent", "struct_jmcpp_1_1_black_list_updated_event.html", null ],
      [ "Jmcpp::ForceLogoutEvent", "struct_jmcpp_1_1_force_logout_event.html", null ],
      [ "Jmcpp::GroupCreatedEvent", "struct_jmcpp_1_1_group_created_event.html", null ],
      [ "Jmcpp::GroupInfoUpdatedEvent", "struct_jmcpp_1_1_group_info_updated_event.html", null ],
      [ "Jmcpp::GroupMemberSilentChangedEvent", "struct_jmcpp_1_1_group_member_silent_changed_event.html", null ],
      [ "Jmcpp::GroupShieldUpdatedEvent", "struct_jmcpp_1_1_group_shield_updated_event.html", null ],
      [ "Jmcpp::LeavedGroupEvent", "struct_jmcpp_1_1_leaved_group_event.html", null ],
      [ "Jmcpp::MessageRetractedEvent", "struct_jmcpp_1_1_message_retracted_event.html", null ],
      [ "Jmcpp::MultiBlackListChangedEvent", "struct_jmcpp_1_1_multi_black_list_changed_event.html", null ],
      [ "Jmcpp::MultiFriendAddedEvent", "struct_jmcpp_1_1_multi_friend_added_event.html", null ],
      [ "Jmcpp::MultiFriendRemarkUpdatedEvent", "struct_jmcpp_1_1_multi_friend_remark_updated_event.html", null ],
      [ "Jmcpp::MultiFriendRemovedEvent", "struct_jmcpp_1_1_multi_friend_removed_event.html", null ],
      [ "Jmcpp::MultiGroupShieldChangedEvent", "struct_jmcpp_1_1_multi_group_shield_changed_event.html", null ],
      [ "Jmcpp::MultiNoDisturbChangedEvent", "struct_jmcpp_1_1_multi_no_disturb_changed_event.html", null ],
      [ "Jmcpp::MultiReceiptChangedEvent", "struct_jmcpp_1_1_multi_receipt_changed_event.html", null ],
      [ "Jmcpp::MultiUnreadMsgCountChangedEvent", "struct_jmcpp_1_1_multi_unread_msg_count_changed_event.html", null ],
      [ "Jmcpp::NoDisturbUpdatedEvent", "struct_jmcpp_1_1_no_disturb_updated_event.html", null ],
      [ "Jmcpp::NullEvent", "struct_jmcpp_1_1_null_event.html", null ],
      [ "Jmcpp::PassAddFriendEvent", "struct_jmcpp_1_1_pass_add_friend_event.html", null ],
      [ "Jmcpp::ReceiptsUpdatedEvent", "struct_jmcpp_1_1_receipts_updated_event.html", null ],
      [ "Jmcpp::RejectAddFriendEvent", "struct_jmcpp_1_1_reject_add_friend_event.html", null ],
      [ "Jmcpp::RejectJoinGroupEvent", "struct_jmcpp_1_1_reject_join_group_event.html", null ],
      [ "Jmcpp::RemovedByFriendEvent", "struct_jmcpp_1_1_removed_by_friend_event.html", null ],
      [ "Jmcpp::RemovedFromGroupEvent", "struct_jmcpp_1_1_removed_from_group_event.html", null ],
      [ "Jmcpp::RequestAddFriendEvent", "struct_jmcpp_1_1_request_add_friend_event.html", null ],
      [ "Jmcpp::RequestJoinGroupEvent", "struct_jmcpp_1_1_request_join_group_event.html", null ],
      [ "Jmcpp::TransCommandEvent", "struct_jmcpp_1_1_trans_command_event.html", null ],
      [ "Jmcpp::UserInfoUpdatedEvent", "struct_jmcpp_1_1_user_info_updated_event.html", null ],
      [ "Jmcpp::UserUpdatedEvent", "struct_jmcpp_1_1_user_updated_event.html", null ]
    ] ],
    [ "Jmcpp::GetRoomsResult", "struct_jmcpp_1_1_get_rooms_result.html", null ],
    [ "Jmcpp::GroupInfo", "struct_jmcpp_1_1_group_info.html", null ],
    [ "Jmcpp::GroupMember", "struct_jmcpp_1_1_group_member.html", null ],
    [ "Jmcpp::Logger", "class_jmcpp_1_1_logger.html", null ],
    [ "Jmcpp::Message", "class_jmcpp_1_1_message.html", null ],
    [ "Jmcpp::ReceiptsUpdatedEvent::MessageReceiptInfo", "struct_jmcpp_1_1_receipts_updated_event_1_1_message_receipt_info.html", null ],
    [ "Jmcpp::MessageReceipts", "struct_jmcpp_1_1_message_receipts.html", null ],
    [ "Jmcpp::MessageSettings", "struct_jmcpp_1_1_message_settings.html", null ],
    [ "Jmcpp::NotDisturbInfo", "struct_jmcpp_1_1_not_disturb_info.html", null ],
    [ "Jmcpp::RoomInfo", "struct_jmcpp_1_1_room_info.html", null ],
    [ "runtime_error", null, [
      [ "Jmcpp::ServerException", "struct_jmcpp_1_1_server_exception.html", null ]
    ] ],
    [ "Jmcpp::UserId", "struct_jmcpp_1_1_user_id.html", null ],
    [ "Jmcpp::UserInfo", "struct_jmcpp_1_1_user_info.html", null ],
    [ "Jmcpp::UserInfoLite", "struct_jmcpp_1_1_user_info_lite.html", null ],
    [ "Jmcpp::UserInfoParam", "struct_jmcpp_1_1_user_info_param.html", null ]
];